# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Home', url: 'Home'}
- {name: 'Step1', url: 'Step1'}
- {name: 'Step2', url: 'Step2'}
- {name: 'Step3', url: 'Step3'}
- {name: 'Step4', url: 'Step4'}
- {name: 'Step5', url: 'Step5}
- {name: 'about', url: 'about'}
- {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'laptop', 'https://www.alt.ac.uk/digital-accessibility-sig'}
- {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
- {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'envelope', link:   'mailto:hello@paulle.ca'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
